#!/bin/bash

################### INPUT ARGS ###################
NORMALIZED_CHIPDATA_FULL=$1
GENE_FILTER_LST=$2
PATIENT_SHEET=$3
VALID_CHIPS=$4
OUTPUT_TBL=$5

NUM_TOP_GENES=200 
ML_MODEL=nu_svm
##################################################

################## PREPARE DATA ##################
echo "... Preparing normalized data"
mkdir -p output/training
mkdir -p output/testing
python ./scripts/prepare_normalized_expr_data.py -i $NORMALIZED_CHIPDATA_FULL -l $GENE_FILTER_LST -c 2 -o1 output/chipdata_geneset_x_valid_chips.txt -o2 output/chipdata_geneset_x_valid_chips_full.txt

echo "... Splitting training/testing sets"
python ./scripts/split_expr_train_vs_test.py -v $VALID_CHIPS -i output/chipdata_geneset_x_valid_chips.txt -tr0 output/training/chipdata.txt -tr1 output/training/valid_chips.txt -te0 output/testing/chipdata.txt -te1 output/testing/valid_chips.txt
##################################################

################ ANALYZE DE GENES ################
echo "... Analyzing DE genes"
Rscript ./scripts/de_analysis.r output/training/chipdata.txt output/training/valid_chips.txt N_vs_P_vs_C 1 0 output/training/top_de_genes.txt
	
echo "... Preparing training/testing datasets"
python ./scripts/convert_expr_for_ml.py -t output/training/top_de_genes.txt -i output/training/chipdata.txt -o output/training/training_set.txt
python ./scripts/convert_expr_for_ml.py -t output/training/top_de_genes.txt -i output/testing/chipdata.txt -o output/testing/testing_set.txt
python ./scripts/incorporate_patient_info.py -p ${PATIENT_SHEET} -d output/training/training_set.txt
python ./scripts/incorporate_patient_info.py -p ${PATIENT_SHEET} -d output/testing/testing_set.txt 
##################################################

################# MODEL TRAINING #################
echo "... Training models"
rm -rf $ML_MODEL
python ./scripts/crc_training.py -i output/training/training_set.txt -a $ML_MODEL -o output/training/${ML_MODEL} -s output/training/predictor_normal_stats.txt
##################################################

################# MODEL TESTING ##################
echo "... Testing prediction"
python ./scripts/crc_prediction.py -i output/testing/testing_set.txt -a $ML_MODEL -m output/training/${ML_MODEL}/${ML_MODEL}_model.pkl -s output/training/predictor_normal_stats.txt -o $OUTPUT_TBL
##################################################

